import { Ubuntu } from "next/font/google";
import "./globals.css";


import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Footer from "@/components/Footer";

// Font configurations
const ubuntu = Ubuntu({
  subsets: ["latin"],
  variable: "--ubuntu",
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "igebra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${ubuntu.variable} font-ubuntu bg-slate-50 overflow-x-clip min-h-screen`} suppressHydrationWarning>

            {children}
        </body>
      </html>
    </ClerkProvider>
  );
}